spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MovieTheater?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm
    serialization:
      write-dates-as-timestamps: false

jwt:
  signerKey: "3aF+lAiyA/tEAeeBtmlou0RwdTwXx0lU6SjH0MYBR7DRt9vyJzlv66uqnqHMP2NW"
  valid-duration: 86400
  refreshable-duration: 36000

initial:
  admin:
    password: admin123

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

